#!/usr/bin/env bash
# Interactive setup script for .env file
# Asks the user for their Gemini API keys (up to 3) and writes a clean .env file.
# Run with: bash scripts/setup-env.sh
set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE=".env"

echo "================================================================"
echo "  EthioJob Hunter — .env setup"
echo "================================================================"
echo ""
echo "This will create $ENV_FILE with your AI provider keys."
echo "Get your free Gemini API keys at: https://aistudio.google.com/apikey"
echo ""
echo "TIP: Each key from a different Google account gives you 1500 req/day."
echo "With 3 keys from 3 accounts, that's 4500 req/day — plenty for syncing."
echo ""

# Read keys (hidden input for security)
read -r -p "Paste Gemini API key #1 (or press Enter to skip): " KEY1
read -r -p "Paste Gemini API key #2 (or press Enter to skip): " KEY2
read -r -p "Paste Gemini API key #3 (or press Enter to skip): " KEY3

# Validate: keys should not have spaces
validate_key() {
  local key="$1"
  local label="$2"
  if [ -z "$key" ]; then
    return 1
  fi
  if [[ "$key" == *" "* ]]; then
    echo "  ⚠️  $label contains spaces — keys should be one continuous string."
    echo "      Stripping spaces automatically..."
    key="${key// /}"
  fi
  if [ ${#key} -lt 20 ]; then
    echo "  ⚠️  $label is too short (${#key} chars) — looks invalid. Skipping."
    return 1
  fi
  if [[ ! "$key" == AIza* ]]; then
    echo "  ⚠️  $label doesn't start with 'AIza' — may not be a real Gemini key."
    echo "      Will save anyway, but verify at https://aistudio.google.com/apikey"
  fi
  echo "$key"
  return 0
}

KEY1_VALID=$(validate_key "$KEY1" "Key 1" || true)
KEY2_VALID=$(validate_key "$KEY2" "Key 2" || true)
KEY3_VALID=$(validate_key "$KEY3" "Key 3" || true)

# Write the .env file
cat > "$ENV_FILE" << EOF
# =============================================================================
# Telegram Job Aggregator — Environment Variables
# Generated by scripts/setup-env.sh
# All AI provider keys stay SERVER-SIDE — they're only used by /api/extract.
# =============================================================================

# ---- AI Providers ----
EOF

if [ -n "$KEY1_VALID" ]; then
  echo "GEMINI_API_KEY=$KEY1_VALID" >> "$ENV_FILE"
  echo "  ✓ Key 1 saved"
fi
if [ -n "$KEY2_VALID" ]; then
  echo "GEMINI_API_KEY_2=$KEY2_VALID" >> "$ENV_FILE"
  echo "  ✓ Key 2 saved (load balancing enabled)"
fi
if [ -n "$KEY3_VALID" ]; then
  echo "GEMINI_API_KEY_3=$KEY3_VALID" >> "$ENV_FILE"
  echo "  ✓ Key 3 saved (load balancing enabled)"
fi

cat >> "$ENV_FILE" << 'EOF'
GEMINI_MODEL=gemini-2.0-flash

# Other providers (uncomment + add key if you have them)
# GROQ_API_KEY=
# GROQ_MODEL=llama-3.1-8b-instant
# DEEPSEEK_API_KEY=
# DEEPSEEK_MODEL=deepseek-chat
# OPENROUTER_API_KEY=
# OPENROUTER_MODEL=google/gemini-flash-1.5

# Local fallback (only if you run Ollama locally)
# OLLAMA_URL=http://localhost:11434
# OLLAMA_MODEL=phi4:latest

# ---- App config ----
NODE_ENV=development
EOF

echo ""
echo "================================================================"
echo "✅  $ENV_FILE created"
echo "================================================================"
echo ""
echo "Next steps:"
echo "  1. Restart the dev server:  Ctrl+C  then  npm run dev"
echo "  2. Look for this line in the terminal output:"
echo "     [ai-router] gemini: N key(s) loaded — load balancing enabled"
echo "  3. Open the PWA → Admin → Debug panel → click 'Test AI provider'"
echo ""
