#!/usr/bin/env bash
# Interactive setup script for .env file
# Run with: bash scripts/setup-env.sh
set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE=".env"

echo "================================================================"
echo "  EthioJob Hunter — .env setup"
echo "================================================================"
echo ""
echo "This will create $ENV_FILE with your AI provider key."
echo ""
echo "RECOMMENDED: DeepSeek"
echo "  - $5.50 free credit on signup (~37K extraction requests)"
echo "  - Works globally (no region blocks)"
echo "  - Get a key at: https://platform.deepseek.com"
echo ""
echo "ALTERNATIVE: Mistral"
echo "  - Free tier with rate limits, no daily cap"
echo "  - Get a key at: https://console.mistral.ai"
echo ""
echo "FALLBACK: OpenRouter"
echo "  - Free tier limited to 50 req/day (use only as backup)"
echo "  - Get a key at: https://openrouter.ai"
echo ""

read -r -p "Paste your DeepSeek API key (sk-...): " DEEPSEEK_KEY
read -r -p "Paste your Mistral API key (optional, press Enter to skip): " MISTRAL_KEY
read -r -p "Paste your OpenRouter API key (optional, press Enter to skip): " OPENROUTER_KEY

# Validate keys
validate_key() {
  local key="$1"
  local label="$2"
  if [ -z "$key" ]; then
    return 1
  fi
  # Strip any whitespace
  key="$(echo "$key" | tr -d '[:space:]')"
  if [ ${#key} -lt 20 ]; then
    echo "  ⚠️  $label is too short (${#key} chars) — skipping"
    return 1
  fi
  echo "$key"
  return 0
}

DEEPSEEK_VALID=$(validate_key "$DEEPSEEK_KEY" "DeepSeek key" || true)
MISTRAL_VALID=$(validate_key "$MISTRAL_KEY" "Mistral key" || true)
OPENROUTER_VALID=$(validate_key "$OPENROUTER_KEY" "OpenRouter key" || true)

if [ -z "$DEEPSEEK_VALID" ] && [ -z "$MISTRAL_VALID" ] && [ -z "$OPENROUTER_VALID" ]; then
  echo ""
  echo "❌ No valid keys provided. Cannot create .env without at least one AI provider."
  echo "   Get a free DeepSeek key at: https://platform.deepseek.com"
  exit 1
fi

# Write the .env file
cat > "$ENV_FILE" << EOF
# Generated by scripts/setup-env.sh
EOF

if [ -n "$DEEPSEEK_VALID" ]; then
  cat >> "$ENV_FILE" << EOF
DEEPSEEK_API_KEY=$DEEPSEEK_VALID
DEEPSEEK_MODEL=deepseek-chat
EOF
  echo "  ✓ DeepSeek key saved (primary provider)"
fi

if [ -n "$MISTRAL_VALID" ]; then
  cat >> "$ENV_FILE" << EOF
MISTRAL_API_KEY=$MISTRAL_VALID
MISTRAL_MODEL=mistral-small-latest
EOF
  echo "  ✓ Mistral key saved (secondary provider)"
fi

if [ -n "$OPENROUTER_VALID" ]; then
  cat >> "$ENV_FILE" << EOF
OPENROUTER_API_KEY=$OPENROUTER_VALID
OPENROUTER_MODEL=nvidia/nemotron-3-nano-30b-a3b:free
EOF
  echo "  ✓ OpenRouter key saved (fallback provider)"
fi

cat >> "$ENV_FILE" << 'EOF'

NODE_ENV=development
EOF

echo ""
echo "================================================================"
echo "✅  $ENV_FILE created"
echo "================================================================"
echo ""
echo "Next steps:"
echo "  1. Restart the dev server:  Ctrl+C  then  npm run dev"
echo "  2. Look for this line in the terminal output:"
echo "     [ai-router] N provider(s) loaded: deepseek, mistral, ..."
echo "  3. Open the PWA → Admin → Debug panel → click 'Test AI provider'"
echo ""
